#!/bin/sh

if [ "$DTR_HOME" == "" ]; then
  echo DTR_HOME not defined
  exit 1
fi

CLASSPATH=$DTR_HOME/dtr.d
CLASSPATH=$CLASSPATH:$DTR_HOME/dtr.d/dtr.jar
CLASSPATH=$CLASSPATH:$DTR_HOME/dtr.d/commons-logging-1.1.jar
CLASSPATH=$CLASSPATH:$DTR_HOME/dtr.d/log4j-1.2.14.jar
CLASSPATH=$CLASSPATH:$DTR_HOME/dtr.d/commons-cli-1.4.jar
CLASSPATH=$CLASSPATH:$DTR_HOME/dtr.d/commons-lang3-3.10.jar
CLASSPATH=$CLASSPATH:$DTR_HOME/dtr.d/postgresql-9.3-1104.jdbc41.jar
CMD="$JAVA_HOME/bin/java -classpath $CLASSPATH -Xmx128m dtr.DTImport $@"
eval $CMD
