#!/bin/sh

DATABASE=dtr
USER=dtr
psql --username=$USER $DATABASE << EOF

DROP TABLE IF EXISTS SERIES_DATA;
DROP TABLE IF EXISTS SERIES;

CREATE TABLE SERIES(
  ID VARCHAR(50) PRIMARY KEY,
  SOURCE VARCHAR(50) NOT NULL,
  SOURCE_ID VARCHAR(50) NOT NULL);

CREATE TABLE SERIES_DATA(
	SERIES_ID VARCHAR(50) REFERENCES SERIES(ID) NOT NULL,
	TS TIMESTAMP NOT NULL,
	VAL REAL NOT NULL);
		
EOF
