#!/bin/sh

DATABASE=dtr
USER=dtr
psql --username=$USER $DATABASE << EOF

DROP TABLE IF EXISTS SERIES;

CREATE TABLE SERIES(
	ID VARCHAR(50) PRIMARY KEY,
	DATESTAMP DATE NOT NULL,
	IDX INTEGER); -- 0..78
EOF
